# Generated by Django 5.2.5 on 2026-05-31 01:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionNASATLX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evaluación')),
                ('tarea_descripcion', models.TextField(blank=True, verbose_name='Descripción de la tarea evaluada')),
                ('demanda_mental', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('demanda_fisica', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('demanda_temporal', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('rendimiento', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('esfuerzo', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('frustracion', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('peso_demanda_mental', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('peso_demanda_fisica', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('peso_demanda_temporal', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('peso_rendimiento', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('peso_esfuerzo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('peso_frustracion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('puntuacion_total', models.FloatField(default=0.0, help_text='Escala 0-100')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos_nasa_tlx/%Y/%m/%d/')),
                ('video_metadata', models.JSONField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('notas_adicionales', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evaluación NASA TLX',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilPWMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_perfil/', verbose_name='Foto de perfil')),
                ('nombre_completo', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decirlo', 'Prefiero no decirlo')], max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('pin', models.CharField(help_text='PIN de 4 dígitos para acceso rápido', max_length=4)),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=5, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('condiciones_medicas', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('psicologo_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('compartir_datos_medicos', models.BooleanField(default=False)),
                ('recibir_recordatorios', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('Commander', 'Commander'), ('Pilot', 'Pilot'), ('Scientist', 'Scientist'), ('Engineer', 'Engineer'), ('MedicalOfficer', 'Medical Officer'), ('PayloadSpecialist', 'Payload Specialist')], max_length=20, null=True)),
                ('experience', models.CharField(blank=True, choices=[('Novice', 'Novice'), ('Experienced', 'Experienced'), ('Veteran', 'Veteran')], max_length=20, null=True)),
                ('baseline_stress', models.FloatField(blank=True, help_text='Baseline stress (1-10)', null=True)),
                ('baseline_fatigue', models.FloatField(blank=True, help_text='Baseline fatigue (1-10)', null=True)),
                ('baseline_cognitive', models.FloatField(blank=True, help_text='Baseline cognitive (0-100)', null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_pwms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil PWMS',
                'verbose_name_plural': 'Perfiles PWMS',
            },
        ),
        migrations.CreateModel(
            name='ZungAnxietyScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('p01_me_siento_mas_nervioso', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='1. Me siento más nervioso y ansioso que de costumbre')),
                ('p02_siento_miedo_sin_razon', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='2. Siento miedo sin razón')),
                ('p03_me_siento_alterado', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='3. Me siento alterado o agitado')),
                ('p04_siento_que_me_desmorono', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='4. Siento que me estoy desmoronando')),
                ('p05_siento_que_todo_bien', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='5. Siento que todo está bien y no pasará nada malo')),
                ('p06_temblor_sacudidas', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='6. Tiemblan mis manos, brazos o piernas')),
                ('p07_dolores_cabeza_cuello', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='7. Tengo dolores de cabeza, cuello o espalda')),
                ('p08_debilidad_fatiga', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='8. Me siento débil y me canso fácilmente')),
                ('p09_siento_calma_tranquilidad', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='9. Me siento calmado y puedo permanecer en calma fácilmente')),
                ('p10_siento_latidos_corazon', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='10. Siento latidos del corazón rápidos')),
                ('p11_mareos', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='11. Tengo mareos o vértigo')),
                ('p12_desmayos', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='12. Siento que me voy a desmayar')),
                ('p13_respiracion_normal', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='13. Puedo respirar normal')),
                ('p14_entumecimiento_hormigueo', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='14. Tengo entumecimiento u hormigueo en dedos, manos o pies')),
                ('p15_dolores_estomacales', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='15. Tengo dolores de estómago o indigestión')),
                ('p16_necesidad_orinar', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='16. Tengo necesidad frecuente de orinar')),
                ('p17_manos_calidas_secas', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='17. Mis manos están normalmente calientes y secas')),
                ('p18_sonrojo_bochorno', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='18. Mi cara se sonroja y siento bochornos')),
                ('p19_duermo_bien_descanso', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='19. Duermo bien y descanso')),
                ('p20_pesadillas', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='20. Tengo pesadillas')),
                ('puntuacion_bruta', models.IntegerField(blank=True, help_text='Suma total de las respuestas', null=True, verbose_name='Puntuación bruta')),
                ('puntuacion_indice', models.IntegerField(blank=True, help_text='Puntuación bruta × 1.25 (escala de 25-100)', null=True, verbose_name='Índice de Ansiedad')),
                ('nivel_ansiedad', models.CharField(blank=True, choices=[('normal', 'Dentro de lo normal (25-44)'), ('minima', 'Ansiedad mínima a moderada (45-59)'), ('marcada', 'Ansiedad marcada a severa (60-74)'), ('extrema', 'Ansiedad extrema (75-100)')], max_length=20, null=True, verbose_name='Nivel de ansiedad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('video_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta del video')),
                ('video_metadata', models.JSONField(blank=True, null=True, verbose_name='Metadatos del video (resolución, fps, etc.)')),
                ('video_size', models.IntegerField(blank=True, null=True, verbose_name='Tamaño del video (bytes)')),
                ('video_duration', models.IntegerField(blank=True, null=True, verbose_name='Duración del video (segundos)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_ansiedad_zung', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Escala de Ansiedad de Zung',
                'verbose_name_plural': 'Escalas de Ansiedad de Zung',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
