# Generated by Django 6.0.5 on 2026-05-25 23:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.CharField(max_length=50)),
                ('escenario', models.CharField(max_length=10)),
                ('sample_id', models.CharField(max_length=120, unique=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('estado_esperado', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_clasificado', models.CharField(blank=True, max_length=30, null=True)),
                ('clasificacion_correcta', models.BooleanField(default=False)),
                ('alerta_esperada', models.BooleanField(default=False)),
                ('alerta_activada', models.BooleanField(default=False)),
                ('alerta_correcta', models.BooleanField(default=False)),
                ('tstart', models.DateTimeField()),
                ('tgen', models.DateTimeField(blank=True, null=True)),
                ('tsync', models.DateTimeField(blank=True, null=True)),
                ('lp_ms', models.FloatField(blank=True, null=True)),
                ('lcr_ms', models.FloatField(blank=True, null=True)),
                ('trs_ms', models.FloatField(blank=True, null=True)),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('energia', 'Energia'), ('agua', 'Agua'), ('oxigeno', 'Oxigeno'), ('co2', 'CO2'), ('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('alimentos', 'Alimentos'), ('temperatura_alimentos', 'Temperatura_Alimentos')], max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.FloatField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'agua'}, on_delete=django.db.models.deletion.CASCADE, to='REMS.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoAlimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porciones_iniciales', models.PositiveIntegerField(default=112, validators=[django.core.validators.MinValueValidator(1)])),
                ('porciones_actuales', models.PositiveIntegerField(default=112, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_tripulantes', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('porciones_por_persona_dia', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('duracion_mision_dias', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='REMS.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoAlimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('comida', 'Comida'), ('cena', 'Cena')], max_length=20)),
                ('personas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('porciones', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('recurso_alimentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='REMS.recursoalimentos')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoCO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentracion', models.FloatField(help_text='Concentración de CO₂ en ppm')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'co2'}, on_delete=django.db.models.deletion.CASCADE, to='REMS.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltaje', models.FloatField()),
                ('corriente', models.FloatField()),
                ('potencia', models.FloatField()),
                ('factor_potencia', models.FloatField(blank=True, null=True)),
                ('frecuencia', models.FloatField(blank=True, null=True)),
                ('potencia_generada_w', models.FloatField(blank=True, help_text='Potencia instantánea generada por los paneles solares en W', null=True)),
                ('energia_generada_wh', models.FloatField(blank=True, help_text='Energía solar acumulada generada en Wh', null=True)),
                ('temperatura_panel_c', models.FloatField(blank=True, help_text='Temperatura estimada o medida del panel solar en °C', null=True)),
                ('potencia_consumida_w', models.FloatField(blank=True, help_text='Potencia instantánea consumida por el hábitat en W', null=True)),
                ('energia_consumida_wh', models.FloatField(blank=True, help_text='Energía acumulada consumida por el hábitat en Wh', null=True)),
                ('balance_w', models.FloatField(blank=True, help_text='Diferencia instantánea entre generación solar y consumo en W', null=True)),
                ('balance_acumulado_wh', models.FloatField(blank=True, help_text='Balance energético acumulado en Wh', null=True)),
                ('soc_bateria_pct', models.FloatField(blank=True, help_text='Estado de carga de la batería en porcentaje', null=True)),
                ('energia_bateria_wh', models.FloatField(blank=True, help_text='Energía restante en el banco de baterías en Wh', null=True)),
                ('capacidad_bateria_wh', models.FloatField(blank=True, help_text='Capacidad total del banco de baterías en Wh', null=True)),
                ('autonomia_h', models.FloatField(blank=True, help_text='Autonomía estimada restante en horas', null=True)),
                ('temperatura_bateria_c', models.FloatField(blank=True, help_text='Temperatura estimada o medida del banco de baterías en °C', null=True)),
                ('estado_energia', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='normal', max_length=20)),
                ('modo_baja_energia', models.BooleanField(default=False, help_text='Indica si el sistema activó el protocolo de baja energía')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'energia'}, on_delete=django.db.models.deletion.CASCADE, to='REMS.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoHumedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Humedad relativa (%)')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'humedad'}, on_delete=django.db.models.deletion.CASCADE, to='REMS.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoOxigeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.FloatField(help_text='Concentración de O₂ en %')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'oxigeno'}, on_delete=django.db.models.deletion.CASCADE, to='REMS.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Temperatura en °C')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'temperatura'}, on_delete=django.db.models.deletion.CASCADE, to='REMS.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAlimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Temperatura en °C')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'temperatura_alimentos'}, on_delete=django.db.models.deletion.CASCADE, to='REMS.recurso')),
            ],
        ),
    ]
